### ISSUE TITLE
Exporting certain info from this chart so that it can be consumed by other charts/applications

### ISSUE THREAD

**Issue by mbaldessari** [validatedpatterns/openshift-data-foundations-chart#13]
I was trying to port https://github.com/validatedpatterns/medical-diagnosis to use this chart and noticed the following pattern. In that pattern they export service url and external url into a [configmap](https://github.com/validatedpatterns/medical-diagnosis/blob/main/charts/all/openshift-data-foundations/templates/cm-odf-servicePoint.yaml). This configmap gets created directly in the namespace that will then reference it:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
  namespace: "{{ .Values.global.xraylab.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
data:
  url: "{{ .Values.odf.serviceUrl }}"
  url-external: "{{ .Values.odf.externalUrl }}.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}"
```

Then applications will use it like this:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: risk-assessment
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/target: '1'
          revisionTimestamp: ''
    spec:
      containers:
      - image: quay.io/rh-data-services/xraylab-risk-assessment:latest
        ports:
        - containerPort: 5000
        env:
...
          valueFrom:
            configMapKeyRef:
              name: service-point
              key: url
```

So I was wondering what our options are to tackle this. Fundamentally this boils down to "Can helm use values from another chart?" The answer to that is pretty much a "No, it cannot"

So I can think of the following approaches of the top of my head:
1. We simply let the chart that needs this replicate those two values somehow on their own. This is probably the simplest approach, although if somebody tweaks the values in the ODF charts that won't be reflected anywhere else.
2.  We add a configmap where we export some of this data. This has the drawback that a configmap is useful only in the namespace where it will be used and the ODF chart has no knowledge of these namespaces. So the other parts of a pattern would still need to find a way to copy this configmap in other namespaces
3. Some other clever mechanism I have not thought of

I am sort of leaning towards 1. but I'd like to get some feeback from others before going down this path
