### ISSUE TITLE
Feature request: enable ODF console plugin

### ISSUE THREAD

**Issue by tomkivlin** [validatedpatterns/openshift-data-foundations-chart#16]
I would like the chart to include the enablement of the ODF console plugin.  I guess ideally the operator configuraiton or storagecluster configuration would take something like `console: true` as input much like other components do (e.g. multi cluster engine).

I have done this via the following - happy to submit a PR if the issue is accepted. Maybe better to use a specific SA or rename existing but I haven't done that yet.

```yaml
# templates/job-enable-console.yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: enable-odf-console
  namespace: {{ .Values.odf.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["odf-console"]}]'
        name: enable-odf-console
        resources: {}  
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.odf.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.odf.jobTerminationGracePeriod }}
```

and add the following to values.yaml:

```yaml

      - name: odf-enable-console
        createRole: true
        apiGroups:
          - 'operator.openshift.io'
        scope:
          cluster: true
        resources:
          - consoles 
        resourceNames:
          - cluster
        verbs:
          - "get"
          - "patch"

# lines not shown

      - name: odf-enable-console
        createBinding: true
        scope:
          cluster: true
          namespace: ""
        subjects:
          kind: ServiceAccount
          name: odf-node-label-sa
          namespace: openshift-storage
          apiGroup: ""
        roleRef:
          kind: ClusterRole
          name: odf-enable-console
```
